font_family JetBrainsMono Nerd Font
font_size 11.5

# Transparency
background_opacity 0.88
background_blur 0

window_padding_width 20

confirm_os_window_close 0
hide_window_decorations yes

cursor_shape block
enable_audio_bell no

foreground #d4d4d4
background #0d0d0d

selection_background #c49a6c
selection_foreground #0d0d0d

cursor #c49a6c

active_border_color #c49a6c
inactive_border_color #222222

color0  #1b1b1b
color1  #b66467
color2  #8c977d
color3  #d9bc8c
color4  #8da3b9
color5  #a988b0
color6  #8aa6a2
color7  #d4d4d4

color8  #808080
color9  #c4746e
color10 #8a9a7b
color11 #c49a6c
color12 #9bb1c8
color13 #b296c0
color14 #9ab7b2
color15 #f5f5f5
